width = float(input('ป้อนความกว้าง : '))
lenght = float(input('ป้อนความยาว : '))
High = float(input('ป้อนความสูง : '))
print('------------------------')
total_area = round((2*(width * lenght + width * High + High * lenght)) / 5)
print(f'ค่าสี่เหลี่ยม {width} {lenght} {High} เพราะฉะนั้นจะต้องใช้สี {total_area}')
print('ค่าสี่เหลี่ยม {} {} {} เพราะฉะนั้นจะต้องใช้สี {}'.format(width,lenght,High,total_area))
print('ค่าสี่เหลี่ยม',width,lenght,High,'เพราะฉะนั้นจะต้องใช้สี',total_area)
print('ค่าสี่เหลี่ยม' +  str(width) + str(lenght) + str(High) + 'เพราะฉะนั้นจะต้องใช้สี' + str(total_area))